.travis.yml
We were missing goveralls and Travis wasn't even telling us of the
error. Bad Travis, bad!
=> build: go get goveralls

fdleak_test.go
When we've already failed the comparison for a previous fd, nothing
should be able to make us return true.
Unfortunately, we were overriding unconditionally the equal boolean
with no regard of the past.
This was found testing the proxy on go tip (what will become 1.9), the
runtime has changed and exposed that bug.
=> fdleak: Don't let Compare() return true when it shouldn't

fdleak_test.go, vm.go
*note: this commit is already in 2.1, after the proxy code was split into its own package. This is just forward porting a commit that has already been reviewed/tested.*
That's a bug we have had for the longest time. There is one such
goroutine per VM and we where quitting it whenever we had an error
writing data to a shim.
However, we may have a number of shim per-VM, one for the initial
container and one for each exec. We can't just quite the whole goroutine
if the write to one of the shim is failing.
This bug was discovered because we know signal "VM lost" when this
goroutine exits, which was causing havoc.
Fixes: https://github.com/01org/cc-oci-runtime/issues/638
=> [foward port for 2.1] proxy: Don't quit the hyper->client IO goroutine when a shim dies

.ci/go-static-checks.sh
We run gofmt with the simplify (-s) option. Some of the rewrite rules
are hidden behind that flag because they break previous go versions.
Editors don't run gofmt with -s by default for that reason and so it's
not unlikely the static checks scripts find something to change.
We can do better than displaying the list of "offending" files, we can
make gofmt display a unified diff with the suggested simplification.
It's just a matter of using the -d flag.
=> ci: Display unified diff with what gofmt wants us to change

cc-proxy.socket.in
We don't need those sockets to be read/writable to the whole world. Only
root is enough.
=> proxy: Restrict the socket and parent directory modes

proxy_test.go, vm.go, vm_test.go
I don't really want to have to queue stdout/err data in the proxy.
To solve that, let's introduce a new constraint. The data path:
shim <-> proxy <-> hyperstart
has to be fully setup before we allow newcontainer/execmd to execute a
new process. While we advise to start the shim as early as possible and
issue the newcontainer/execcmd command after that, we need to
synchronize somewhere. The easier way of doing that is to stall the
newcontainer/execcmd commands until we see the corresponding shim
registering itself.
Fixes: https://github.com/clearcontainers/proxy/issues/21
=> exec should wait for shim

fdleak_test.go
When a test fails, we may not generate a fd snapshot and end up in
Compare with nil snapshot(s).
Compare() should handle that case gracefully instead of generating a
panic.
=> fdleak: Handle nil snapshots in Compare

proxy.go, proxy_test.go
Even when we are not allocating some IO streams, the caller can expect to receive a valid URL.
=> proxy: Always return valid URL

README.md
The opening ( has to be just after ] or the md parser doesn't understand
this is a [label](url) construct.
=> README: Fix URL markup

vm.go, vm_test.go
In some cases, we don't need to communicate with the process inside the
VM and don't care about its stdout/err for instance.
This is the case for the pause container when creating a pod with
virtcontainers.
Fixes: https://github.com/clearcontainers/proxy/issues/32
=> vm: Allow newcontainer and execcmd without an I/O token

vm.go, vm_test.go
In:
commit 316d6e2acee64c0f55db138a47e0aed4e1ebb955
Author: Damien Lespiau <damien.lespiau@intel.com>
Date:   Wed Apr 12 18:39:26 2017 +0100
vm: Allow newcontainer and execcmd without an I/O token
We tried to not associate a session (and the corresponding hyperstart
sequence numbers) to containers for which we don't want to send stdin
nor receive stdout/stderr data.
Unfortunately, hyperstart requires us to provide a sequence number. To
work around that, we create a "null session" for every VM with its own
sequence numbers. The proxy will not allocate a Token for null sessions
(no shim can ever try to claim that session) and will discard data of
processes using that null session.
=> vm: Introduce a null session for executions without tokens

Makefile, cc-proxy.service.in, cc-proxy.socket.in
Some paths provided in the cc-proxy.service and cc-proxy.socket were both relying on legacy path names from cc-oci-runtime. This directly led the cc-proxy service to be not started as expected when the proxy socket was used.
=> cc-proxy: Fix systemd socket and service

protocol_test.go
Debugging another issue I found that the protocol tests were leaving
goroutines behind.
Properly close the server goroutine for each test.
=> protocol: Fix dangling goroutines in the tests

proxy_test.go, vm.go
While working in the shim/runtime stind sync, I've done a few clean-ups. No need to wait for that work to be finished to review and merge those ones.
=> A bit of refactoring/cleanup

proxy.go
Because this ID needs to be unique per client, incrementing it before
assigning it.  Otherwise, if two requests are serviced at the same
time, there is a potential for both peers to have the same ID.  Can
also initialize the per-client ID to 0 instead of 1 before servicing
requests.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
=> Prevent race condition with the per-client ID

.pullapprove.yml, OWNERS
To prevent PRs from being blocked as PR pushers are also usually PR
approvers.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> OWNERS: Add 2 more approvers

proxy.go
While re-factoring the code to use logrus, I noticed we were still racy in our use of atomic operations. This time we should be good!
=> Fix /for real/ the use of atomic inc for the client ID

.ci/go-lint.sh
This can take some time and travis times out because it hasn't received
any message on stdout/stderr for 10 minutes.
There are a couple of ways to solve that, making the installation for
verbose may alleviate the problem a bit.
=> ci: Make the installation of linters verbose

client/client.go, proxy.go, proxy_test.go, vm.go, vm_test.go
A somewhat long-winded PR that should remove the need to start the shim as stopped. We finish the work to started to synchronise runtime, shim and the process inside the VM without queuing data. It can be a bit fiddly so the code is somewhat heavily documented and tested.
=> Make the shim wait for the process to be started before forwarding stdin and signals

.ci/go-lint.sh, Gopkg.lock, api/frame.go, api/frame_test.go, api/payload.go, client/client.go, protocol.go, proxy.go, proxy_test.go, vendor/github.com/Sirupsen/logrus/hooks/test/test.go, vendor/github.com/Sirupsen/logrus/hooks/test/test_test.go, vm.go
This PR adds a new log stream type. Clients can use it to send structured log entries with a few predefined fields to the proxy.
=> Add support for clients to send log entries to the proxy

proxy_test.go, vm.go
In case the shim receives a signal, it sends it to the proxy and the proxy has to figure out which container is affected by this signal. The current implementation provides the VM ID (called also pod ID), but this is not right in case we have the pod ID different from the container ID, or in case several containers are running on the same pod.
This patch creates a new field containerID in the Session structure so that we can fill this container ID when the command newcontainer is issued and actually use this information when a signal has to be issued.
=> vm: Assign a container ID to each session

.ci/go-test.sh
We're actually using the atomic counters when running our tests because
we run them with -race (2 lines later). We should set the mode of the
resulting coverage file to match this.
=> tests: Produce a coverage file with atomic mode

.ci/go-lint.sh, .ci/go-test.sh, proxy_test.go
ci: Include coverage data of the 'client' package in the main tests
The main tests make heavy usage of the client package. The -coverpkg
option allows to include more package than only the package currently
tested in the coverage data.
Including the client package shows we indeed cover quite a bit of it
(80%) from the main tests.
=> Include coverage data of the 'client' package when running the main tests

proxy.go
This verify the socket path length according to
http://man7.org/linux/man-pages/man7/unix.7.html.
The proxy fails correctly when the socket path is too long, but the
message is too generic:
```
init: couldn't create AF_UNIX socket:
listen unix SOCKET_PATH: bind: invalid argument
```
Fixes #78
=> cli: Better error message for too long socket path

cc-proxy.service.in
We were hitting this limit before hitting memory limits in our density
test. Remove it. Linux stiff has a global limit that will apply, of
course.
Fixes: https://github.com/01org/cc-oci-runtime/issues/1008
=> proxy: Lift the numbers of opened file descriptors limit

client/client.go, protocol.go, proxy.go, proxy_test.go, vm.go
Until now, hyperstart was never sending data along with the response to commands we cared about. Julio wants to add a ps message that will send some data back though, so let's support that.
We can probably do nice things in the new agent with this as well
=> Forward hyperstart response to clients

.ci/go-test.sh
Since commit f833c18, the package definition has slightly changed and
the local tests haven't been updated to understand the new format.
=> tests: Fix local tests

.ci/go-lint.sh, vm.go
In case the call to SendCtlMessage() was returning an error, the
response object was nil, but it was used anyway.
This patch makes sure we are not using the response handler in
case we got an error.
=> vm: Check SendCtlMessage() return to avoid a segmentation fault

Makefile
PR #87 inadvertently broke the build setting the default socket path
variable. This appears to be due to a bug in "go build" whereby it
accepts any number of -ldflags "-X ..." options, but only actually
honours the last one. On PR #87 this meant that the Version variable
was set, whilst DefaultSocketPath was silently ignored and its value
defaulted to "".
Fixes #90.
=> build: Unbreak DefaultSocketPath.

.ci/run.sh, .ci/setup.sh, .ci/teardown.sh
This commit adds the CI scripts that will execute the functional
and integration tests from the clearcontainers/tests repository.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
=> CI: Add ci scripts that execute tests on SemaphoreCI

.pullapprove.yml, OWNERS
Add @grahamwhaley as an additional project approver.
Fixes #93.
=> CI: Add additional project approver

client/client.go, proxy.go, proxy_test.go, vm.go
Because a state transition from "ready" to "stopped" is possible
for a container created by virtcontainers/runtime, we can end up
with situations where the proxy waits for the shim process to start
so that it can forward a KILL or TERM signal, leading to a deadlock.
Instead, we want the proxy to be smarter, meaning terminate the shim
by himself. Indeed, there is no process/container running inside the
VM, meaning that the corresponding shim will never receive the exit
code from the VM unless the proxy takes care of this.
Fixes #97
=> proxy: Handle KILL and TERM signals when process not running

proxy_test.go
Unit tests in go version devel +e3f3ade are failing
because URL does not match.
Fix match with the needed prefix given in e3f3ade .
Fixes: #115
=> build: Fix unit tests built using go tip

Makefile
Update release version according to new Clear Containers release.
Fixes: #113
=> Release: 3.0.0-beta.2

docs/ksm.md, ksm.go, ksm_test.go, main_test.go, proxy.go, proxy_test.go
We set KSM settings (when available) from `cc-proxy`.
Our default setting is the aggressive one, as we're trying to share as much memory as possible. The default KSM setting knob can be selected from the `cc-proxy` command line (`cc-proxy -ksm`)
The initial KSM settings are restored when the proxy terminates.
=> KSM tuning

README.md
We need to replace build badges since we are not using Travis CI
anymore.
Fixes #126
=> readme: Replace Travis build badges with Jenkins ones

README.md
This commit updates the build badges for Ubuntu 16.04 and 17.04
jenkins jobs since their names changed.
It also adds the build badge related to Fedora 26.
Fixes #133
=> readme: Update build badges

proxy.go
Switch from second-resolution timestamps to nanosecond-resolution for
greater precision and consistency with the runtime and agent.
Fixes #135.
=> logging: Use nanosecond timestamps

Makefile
Version bump for Clear Contianers 3.0.2
- logging: Use nanosecond timestamps
- readme: Update build badges
- Make all log entries parseable
b43cbce logging: Use nanosecond timestamps
db0cae7 readme: Update build badges
ac457b2 logging: Fix logging of hex messages
0975081 logging: Ensure correct quoting of message data
Fixes: #137
=> release: Clear Contianers 3.0.2

proxy.go
Override the default golang panic handling by printing a full traceback
(not just for the current goroutine) and coredumping to allow
crash-handling programs like apport to log the details.
Fixes #141.
=> init: coredump on internal error

ksm.go
We need to release the lock before pushing data into the kick channel.
If we push while holding the lock and the throttle loop is waiting for
the KSM lock, we will deadlock.
Fixes #143
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> ksm: Fix deadlock

Makefile
Fixed deadlock when using ksm throttle.
Overrided the default golang panic to printing a full
traceback to allow crash-handling programs like
apport to log the details.
- ksm: Fix deadlock
- init: coredump on internal error
3cb3823 ksm: Fix deadlock
e9ba5cb init: coredump on internal error
=> release: 3.0.3

.ci/run.sh
The run.sh script has docker tests that are already
covered by our testsuite in the tests repository.
This commit removes those tests.
This commit also changes the way the tests are called in
the tests repository to allow execute OpenShift tests if
the OPENSHIFT_CI envar is set to true.
Fixes: #139
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
=> CI: remove tests from run.sh script

proxy.go
Add a name= and pid= field to the log entries for consistency with the
runtime.
Fixes #148.
=> logging: Add name and PID fields

cc-proxy.service.in
Specify the restart behaviour in the service file to ensure that if the
proxy exits for any reason (except being told to by `systemctl(1)`), it
will be automatically restarted.
Fixes #152.
=> behaviour: Restart on exit

Gopkg.lock, proxy.go, proxy_test.go, vendor/github.com/sirupsen/logrus/hooks/syslog/README.md, vendor/github.com/sirupsen/logrus/hooks/syslog/syslog.go, vendor/github.com/sirupsen/logrus/hooks/syslog/syslog_test.go, vm.go
Allow the proxy to be run for a single pod.
This branch allows multiple proxies to be run on a single system, one per pod. Note that it also permits this behaviour even when the proxy is run as a system-level systemd service.
=> One proxy per vm

proxy.go
In case the proxy was getting an empty message through the stdin
stream from the shim, it was not sending anything to the agent.
Unfortunately, doing such a thing was preventing the agent from
receiving EOF on stdin.
This patch removes this special handling case, and forward every
input from the shim to the agent.
Fixes #169
=> stdin: Forward all stream input coming from the shim

Makefile
- stdin: Forward all stream input coming from the shim
- One proxy per vm
d0cd3c3 stdin: Forward all stream input coming from the shim
bc4d5ca API: Shutdown pod instance on unregister
2386a5a KSM: Only setup when running as system instance
c9af303 logging: Redirect pod instance log output to syslog
8c49c97 logging: Add support for syslog
ff4e478 network: Add URI parameter to getSocketPath()
336cf8e errors: Fix typo in error message
Fixes: #171
=> release: Clear Containers 3.0.8

proxy.go
Previously, the identifier used for each proxy log message specified
the full path to the proxy binary. This meant that to select proxy log
messages it was necessary to specify:
```
$ sudo journalctl -t /usr/libexec/clear-containers/cc-proxy
```
Now, the user can perform the same action with a simple:
```
$ sudo journalctl -t cc-proxy
```
Fixes #180.
=> logging: Ensure journald identifier is simply "cc-proxy"

Gopkg.lock, Gopkg.toml, vendor/github.com/containers/virtcontainers/Gopkg.lock, vendor/github.com/containers/virtcontainers/Gopkg.toml, vendor/github.com/containers/virtcontainers/agent.go, vendor/github.com/containers/virtcontainers/asset.go, vendor/github.com/containers/virtcontainers/asset_test.go, vendor/github.com/containers/virtcontainers/bridge.go, vendor/github.com/containers/virtcontainers/bridge_test.go, vendor/github.com/containers/virtcontainers/cc_proxy.go, vendor/github.com/containers/virtcontainers/cc_proxy_test.go, vendor/github.com/containers/virtcontainers/container.go, vendor/github.com/containers/virtcontainers/container_test.go, vendor/github.com/containers/virtcontainers/hyperstart.go, vendor/github.com/containers/virtcontainers/kata_proxy.go, vendor/github.com/containers/virtcontainers/kata_proxy_test.go, vendor/github.com/containers/virtcontainers/no_proxy.go, vendor/github.com/containers/virtcontainers/no_proxy_test.go, vendor/github.com/containers/virtcontainers/noop_agent.go, vendor/github.com/containers/virtcontainers/noop_agent_test.go, vendor/github.com/containers/virtcontainers/noop_proxy.go, vendor/github.com/containers/virtcontainers/pkg/hyperstart/types.go, vendor/github.com/containers/virtcontainers/pod.go, vendor/github.com/containers/virtcontainers/proxy.go, vendor/github.com/containers/virtcontainers/proxy_test.go, vendor/github.com/containers/virtcontainers/qemu.go, vendor/github.com/containers/virtcontainers/qemu_test.go, vendor/github.com/containers/virtcontainers/sshd.go
This is mainly for the changes introduces in hyperstart container
for specifying system mount information
Virtcontainers Shortlog:
71ce0c8 proxy: Implement Kata Containers proxy
8f9a2e0 proxy: Implement no_proxy generic case
2e2d33c agent: Introduce new functions to agent interface
05cec52 hyperstart: Change the path where rootfs is bind-mounted
d0051aa agent: Pass information about  the "-v /dev:/dev"  case
bdc815d mounts: Deduce additional information about system mounts
7c88153 vendor: switch to govmm
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
=> vendor: Vendor latest virtcontainers.

README.md
Briefly state that Clear Containers now uses a proxy instance for each
virtual machine.
Fixes #193.
=> doc: State one proxy per VM is now used

.ci/setup.sh
Change the `checkcommits` config to not require an issue for release
PRs.
Fixes #202.
=> CI: Don't require an issue for release PRs

fdleak_test.go, ksm_test.go
Close all KSM related fds that we create in our KSM tests.
While these are left open while running the proxy_test.go tests,
where detecting leaking file descriptors is relevant, it looks like
the open ksm fds get closed by the go runtime in the newer version
of Go leading to different before and after file descriptor snapshots in
the proxy_test.go tests.
Fixes #198
=> Fix file descriptor leak tests

Gopkg.lock, Gopkg.toml, vendor/github.com/containers/virtcontainers/Gopkg.lock, vendor/github.com/containers/virtcontainers/Gopkg.toml, vendor/github.com/containers/virtcontainers/README.md, vendor/github.com/containers/virtcontainers/api_test.go, vendor/github.com/containers/virtcontainers/container.go, vendor/github.com/containers/virtcontainers/container_test.go, vendor/github.com/containers/virtcontainers/filesystem.go, vendor/github.com/containers/virtcontainers/filesystem_test.go, vendor/github.com/containers/virtcontainers/hyperstart_agent.go, vendor/github.com/containers/virtcontainers/hypervisor.go, vendor/github.com/containers/virtcontainers/hypervisor_test.go, vendor/github.com/containers/virtcontainers/kata_agent.go, vendor/github.com/containers/virtcontainers/network.go, vendor/github.com/containers/virtcontainers/pkg/hyperstart/types.go, vendor/github.com/containers/virtcontainers/qemu.go, vendor/github.com/containers/virtcontainers/qemu_amd64.go, vendor/github.com/containers/virtcontainers/qemu_arch_base.go, vendor/github.com/containers/virtcontainers/qemu_arm64.go, vendor/github.com/containers/virtcontainers/qemu_test.go, vendor/github.com/containers/virtcontainers/shim.go, vendor/github.com/containers/virtcontainers/utils.go, vendor/github.com/containers/virtcontainers/utils_test.go
Bring the CPU constraints changes.
12f35ce qemu: enable CPU hotplug
925a70c pod: hot add/remove vCPUs before starting containers
4a84438 qemu: Add support for CPU hot add/remove
c17c48d vendor: Constraint containerd vendoring
c9996f3 filesystem: set correct access mode for pod dir tree
4f9cb18 kata_agent: Add nouuid option for xfs filesystem
085848b kata_agent: Provide hotplugged device the right rootfs path
9ef18a6 kata_agent: Update host and guest paths for Kata
2c88b8e kata_agent: Wait for rootfs if it is a hotplugged device
15a4d17 kata_agent: Support block device passthrough
fd5b27f vendor: Update Kata agent protocol
0519e89 check: lint: ineffassign in qemu.go
ae661c5 network: Fix lint errors
5c73774 shim: Start shims inside PID namespace
6d7f6e5 shim: Add ability to enter any set of …
=> vendor: Re-vendor virtcontainers
